# Generated by Django 4.1.7 on 2023-03-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('price', models.FloatField(verbose_name='baasy')),
                ('image', models.ImageField(upload_to='images/products/')),
                ('quantity', models.IntegerField(verbose_name='kolichestvo')),
                ('discount', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
