# Generated by Django 4.2.1 on 2023-05-15 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_order_ordered_items_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('addres', models.CharField(max_length=100, verbose_name='адрес дома')),
                ('phone', models.CharField(max_length=50, verbose_name='номер телефон')),
                ('emil', models.CharField(max_length=100, verbose_name='email')),
                ('pasword', models.CharField(max_length=100, verbose_name='password')),
                ('created', models.DateField(auto_now=True, verbose_name='date_time')),
                ('cart', models.IntegerField(verbose_name='номер карта')),
                ('tpye_delivery', models.IntegerField(choices=[(1, 'Доставка'), (2, 'Я сам возьму')], verbose_name='Type_delivery')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
            preserve_default=False,
        ),
    ]
