# Generated by Django 4.2.1 on 2023-05-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_category_use_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='cart',
            field=models.CharField(max_length=50, verbose_name='номер карта'),
        ),
    ]
