# Generated by Django 4.2.1 on 2023-05-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('addres', models.CharField(max_length=100, verbose_name='адрес дома')),
                ('phone', models.CharField(max_length=50, verbose_name='номер телефон')),
                ('emil', models.CharField(max_length=100, verbose_name='email')),
                ('pasword', models.CharField(max_length=100, verbose_name='password')),
                ('created', models.DateField(auto_now=True, verbose_name='date_time')),
                ('cart', models.CharField(max_length=50, verbose_name='номер карта')),
                ('tpye_delivery', models.IntegerField(choices=[(1, 'Доставка'), (2, 'Я сам возьму')], verbose_name='Type_delivery')),
            ],
        ),
    ]
