# Generated by Django 4.2.1 on 2023-05-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='2000-09-12', verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='floor_pol',
            field=models.IntegerField(choices=[(1, 'Женщина'), (2, 'Мужчина')], default=1, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
