# Generated by Django 4.2.1 on 2023-05-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_register_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
        migrations.AddField(
            model_name='register',
            name='passworld',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
