# Generated by Django 4.2.1 on 2023-05-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_register_email_register_passworld'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(blank=True, max_length=1004),
        ),
    ]
